// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCategoriesApiCategoriesGetData, GetCategoriesApiCategoriesGetErrors, GetCategoriesApiCategoriesGetResponses, GetEpisodeApiEpisodesIdGetData, GetEpisodeApiEpisodesIdGetErrors, GetEpisodeApiEpisodesIdGetResponses, GetEpisodesApiEpisodesGetData, GetEpisodesApiEpisodesGetErrors, GetEpisodesApiEpisodesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Episodes
 */
export const getEpisodesApiEpisodesGet = <ThrowOnError extends boolean = false>(options?: Options<GetEpisodesApiEpisodesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEpisodesApiEpisodesGetResponses, GetEpisodesApiEpisodesGetErrors, ThrowOnError>({
        url: '/api/episodes',
        ...options
    });
};

/**
 * Get Episode
 */
export const getEpisodeApiEpisodesIdGet = <ThrowOnError extends boolean = false>(options: Options<GetEpisodeApiEpisodesIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetEpisodeApiEpisodesIdGetResponses, GetEpisodeApiEpisodesIdGetErrors, ThrowOnError>({
        url: '/api/episodes/{id}',
        ...options
    });
};

/**
 * Get Categories
 */
export const getCategoriesApiCategoriesGet = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesApiCategoriesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCategoriesApiCategoriesGetResponses, GetCategoriesApiCategoriesGetErrors, ThrowOnError>({
        url: '/api/categories',
        ...options
    });
};
