// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Category
 */
export type Category = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    type: CategoryType | null;
};

/**
 * CategoryBase
 */
export type CategoryBase = {
    /**
     * Id
     */
    id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    type: CategoryType | null;
};

/**
 * CategoryType
 */
export type CategoryType = 'topic' | 'location' | 'character' | 'time_period';

/**
 * EpisodeWithCategories
 */
export type EpisodeWithCategories = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Categories
     */
    categories?: Array<CategoryBase>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Page[Category]
 */
export type PageCategory = {
    /**
     * Items
     */
    items: Array<Category>;
    /**
     * Total
     */
    total?: number | null;
    /**
     * Page
     */
    page: number | null;
    /**
     * Size
     */
    size: number | null;
    /**
     * Pages
     */
    pages?: number | null;
};

/**
 * Page[EpisodeWithCategories]
 */
export type PageEpisodeWithCategories = {
    /**
     * Items
     */
    items: Array<EpisodeWithCategories>;
    /**
     * Total
     */
    total?: number | null;
    /**
     * Page
     */
    page: number | null;
    /**
     * Size
     */
    size: number | null;
    /**
     * Pages
     */
    pages?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetEpisodesApiEpisodesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string;
        /**
         * Order
         */
        order?: string;
        /**
         * Categories
         * Comma-separated list of category IDs
         */
        categories?: string;
        /**
         * Page
         * Page number
         */
        page?: number;
        /**
         * Size
         * Page size
         */
        size?: number;
    };
    url: '/api/episodes';
};

export type GetEpisodesApiEpisodesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEpisodesApiEpisodesGetError = GetEpisodesApiEpisodesGetErrors[keyof GetEpisodesApiEpisodesGetErrors];

export type GetEpisodesApiEpisodesGetResponses = {
    /**
     * Successful Response
     */
    200: PageEpisodeWithCategories;
};

export type GetEpisodesApiEpisodesGetResponse = GetEpisodesApiEpisodesGetResponses[keyof GetEpisodesApiEpisodesGetResponses];

export type GetCategoriesApiCategoriesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category type
         */
        type?: CategoryType;
        /**
         * Page
         * Page number
         */
        page?: number;
        /**
         * Size
         * Page size
         */
        size?: number;
    };
    url: '/api/categories';
};

export type GetCategoriesApiCategoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoriesApiCategoriesGetError = GetCategoriesApiCategoriesGetErrors[keyof GetCategoriesApiCategoriesGetErrors];

export type GetCategoriesApiCategoriesGetResponses = {
    /**
     * Successful Response
     */
    200: PageCategory;
};

export type GetCategoriesApiCategoriesGetResponse = GetCategoriesApiCategoriesGetResponses[keyof GetCategoriesApiCategoriesGetResponses];
