// This file is auto-generated by @hey-api/openapi-ts

/**
 * Episode
 */
export type Episode = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Published At
     */
    published_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Page[Episode]
 */
export type PageEpisode = {
    /**
     * Items
     */
    items: Array<Episode>;
    /**
     * Total
     */
    total?: number | null;
    /**
     * Page
     */
    page: number | null;
    /**
     * Size
     */
    size: number | null;
    /**
     * Pages
     */
    pages?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetEpisodesApiEpisodesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         * Page number
         */
        page?: number;
        /**
         * Size
         * Page size
         */
        size?: number;
    };
    url: '/api/episodes';
};

export type GetEpisodesApiEpisodesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEpisodesApiEpisodesGetError = GetEpisodesApiEpisodesGetErrors[keyof GetEpisodesApiEpisodesGetErrors];

export type GetEpisodesApiEpisodesGetResponses = {
    /**
     * Successful Response
     */
    200: PageEpisode;
};

export type GetEpisodesApiEpisodesGetResponse = GetEpisodesApiEpisodesGetResponses[keyof GetEpisodesApiEpisodesGetResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};