"""Initial migration

Revision ID: 2c5858cce373
Revises:
Create Date: 2025-07-22 14:54:51.296212

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c5858cce373"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_episode_published_at"),
        "episode",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_title"), "episode", ["title"], unique=False
    )
    op.create_table(
        "ingestionposition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_episode_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingestionposition")
    op.drop_index(op.f("ix_episode_title"), table_name="episode")
    op.drop_index(op.f("ix_episode_published_at"), table_name="episode")
    op.drop_table("episode")
    # ### end Alembic commands ###
