"""Add category type

Revision ID: 59408ec7c8ff
Revises: 54f194c1857a
Create Date: 2025-09-25 10:09:20.956156

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59408ec7c8ff"
down_revision = "54f194c1857a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categorytype_enum = sa.Enum(
        "TOPIC", "LOCATION", "CHARACTER", "TIME_PERIOD", name="categorytype"
    )
    categorytype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "category",
        sa.Column(
            "type",
            sa.Enum(
                "TOPIC",
                "LOCATION",
                "CHARACTER",
                "TIME_PERIOD",
                name="categorytype",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_category_type"), "category", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_type"), table_name="category")
    op.drop_column("category", "type")
    # ### end Alembic commands ###
